---
- hosts: all
  become: yes
  tasks:
  - name: installing multiple packages
    apt: 
      name: tree
      state: present

  - name: installing wget
    apt:
      name: wget
      state: present

  - name: installing curl
    apt:
      name: curl
      state: present

  - name: install apache2
    apt:
      name: apache2
      state: present
